on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v6

      - name: Setup Corepack (for PNPM)
        run: corepack enable

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm eslint .

      - name: Type check
        run: pnpm tsc --noEmit
    
  publish:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: Setup Corepack (for PNPM)
        run: corepack enable

      - name: Setup NPM
        run: npm i -g npm@latest

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm tsc

      - name: Publish package
        run: npm publish
  
  gh-page:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      # Setup
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: latest
      
      - name: Setup Corepack (for PNPM)
        run: corepack enable
      
      - name: Install dependency
        run: pnpm install --frozen-lockfile
      
      - name: Build
        # env:
        #   BASE_URL: ${{ github.event.repository.name }}/
        run: pnpm typedoc

      # Pack artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs_dist/
      
      # Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4